### ISSUE TITLE
List component accept / receive each new rows update

### ISSUE THREAD

**Issue by okaprinarjayatiket** [researchgate/react-intersection-list#44]
## Expected behavior
I need `<List />` component accept / receive each new rows update. Because my app characteristic is doing interval request to API each 1 second, and some request randomly will get new rows. When get new rows, i will append the new rows to existing rows. 

## Current behavior
The problem is `<List />` doesn't accept / receive the newest rows appended to existing rows. I think it's because `<List />` extending `PureComponent` . I think `<List />` should extend `Component`

## Steps to reproduce

1. 
2.
3.
4.

## Context (environment)

* **Version**: 
* **Platform**:  macOs 64 bit High Sierra

**Comment by Rendez** [comment]
You can use `items` as an array which will be used for comparison. If `items` contains a different length OR is a different array, then the list will re-render.
