### ISSUE TITLE
Incorrect return type for onIntersection

### ISSUE THREAD

**Issue by petr-hajek** [researchgate/react-intersection-list#85]
## Expected behavior
According to the docs onIntersection should return void
`(size: number, pageSize: number) => void`

## Current behavior
Return type is undefined
` onIntersection?: (nextSize: number, pageSize: number) => undefined;`

**Comment by Rendez** [comment]
I'm planning to migrate this lib to TS, so this will be solved then. If you need this now, would you mind opening a PR?
